# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Acc_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from PyQt5.QtCore import Qt


class Ui_MainWindow(object):

    def insert_data_in_tablewidget(self, tablewidget):
        self.conn = sqlite3.connect('data.db')
        sql_select_acc = "SELECT maGV, hoTenGV, tenDangNhap, matKhau FROM Taikhoans WHERE quyen = 'us';"
        self.result_acc = self.conn.execute(sql_select_acc)
        self.num_acc = len(self.conn.execute(sql_select_acc).fetchall())

        self.tableWidget.setRowCount(self.num_acc)

        for index_row, data_row in enumerate(self.result_acc):
            # print(index_row, data_row)
            for index_col, data_col in enumerate(data_row):
                # print(index_col, data_col)
                data = QtWidgets.QTableWidgetItem(str(data_col))
                data.setTextAlignment(Qt.AlignCenter)
                tablewidget.setItem(index_row, index_col, data)
        self.conn.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 531, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)

        self.tableWidget.setHorizontalHeaderLabels(['Mã giáo viên','Họ tên giáo viên', 'Tên đăng nhập', 'Mật khẩu'])
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 150)

        self.btn_them = QtWidgets.QPushButton(self.centralwidget)
        self.btn_them.setGeometry(QtCore.QRect(600, 100, 180, 40))
        self.btn_them.setObjectName("btn_them")
        self.btn_sua = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sua.setGeometry(QtCore.QRect(600, 170, 180, 40))
        self.btn_sua.setObjectName("btn_sua")
        self.btn_xoa = QtWidgets.QPushButton(self.centralwidget)
        self.btn_xoa.setGeometry(QtCore.QRect(600, 240, 180, 40))
        self.btn_xoa.setObjectName("btn_xoa")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 771, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_thoat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_thoat.setGeometry(QtCore.QRect(600, 310, 180, 40))
        self.btn_thoat.setObjectName("btn_thoat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ỨNG DỤNG ĐIỂM DANH BẰNG KHUÔN MẶT"))
        self.btn_them.setText(_translate("MainWindow", "Thêm"))
        self.btn_sua.setText(_translate("MainWindow", "Sửa"))
        self.btn_xoa.setText(_translate("MainWindow", "Xóa"))
        self.label.setText(_translate("MainWindow", "QUẢN LÝ TÀI KHOẢN"))
        self.btn_thoat.setText(_translate("MainWindow", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.insert_data_in_tablewidget(ui.tableWidget)
    MainWindow.show()
    sys.exit(app.exec_())
