# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ListStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def InsertDataInTableWidget(self, tableWidget, urlDatabase='data.db'):
        conn = sqlite3.connect(urlDatabase)
        sqlSelectAllStudent = "SELECT DISTINCT * FROM Sinhviens ORDER BY ten"
        resultSelectAllStudent = conn.execute(sqlSelectAllStudent).fetchall()
        conn.close()
        # print(resultSelectAllStudent)
        self.tableWidget.setRowCount(len(resultSelectAllStudent))

        for index_row, data_row in enumerate(resultSelectAllStudent):
            # print(index_row, data_row)
            for index_col, data_col in enumerate(data_row):
                # print(index_col, data_col)
                data = QtWidgets.QTableWidgetItem(str(data_col))
                data.setTextAlignment(Qt.AlignCenter)
                tableWidget.setItem(index_row, index_col, data)

    def GetMaSV(self):
        indexRow = self.tableWidget.currentRow()
        maSV = self.tableWidget.item(indexRow, 0).text()
        # print(maSV)
        return maSV

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 1050, 520))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        lstLabels = ('Mã sinh viên', 'Họ đệm', 'Tên', 'Ngày sinh', 'Giới tính', 'Ngành học', 'Lớp cố định')
        self.tableWidget.setHorizontalHeaderLabels(lstLabels)
        self.tableWidget.setColumnWidth(0, 120)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(5, 200)
        self.tableWidget.setColumnWidth(6, 170)

        self.btnThem = QtWidgets.QPushButton(self.centralwidget)
        self.btnThem.setGeometry(QtCore.QRect(1070, 130, 120, 40))
        self.btnThem.setObjectName("btnThem")
        self.btnSua = QtWidgets.QPushButton(self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(1070, 210, 120, 40))
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(1070, 290, 120, 40))
        self.btnXoa.setObjectName("btnXoa")
        self.btnThoat = QtWidgets.QPushButton(self.centralwidget)
        self.btnThoat.setGeometry(QtCore.QRect(1070, 370, 120, 40))
        self.btnThoat.setObjectName("btnThoat")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1050, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.btnXoa.clicked.connect(self.GetMaSV)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnThem.setText(_translate("MainWindow", "Thêm"))
        self.btnSua.setText(_translate("MainWindow", "Sửa"))
        self.btnXoa.setText(_translate("MainWindow", "Xóa"))
        self.btnThoat.setText(_translate("MainWindow", "Thoát"))
        self.label.setText(_translate("MainWindow", "DANH SÁCH SINH VIÊN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.InsertDataInTableWidget(ui.tableWidget, '../data.db')
    MainWindow.show()
    sys.exit(app.exec_())
