# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_btnQuanSV(object):

    login = None
    teacher_name = None

    def setupUi(self, btnQuanSV):
        btnQuanSV.setObjectName("btnQuanSV")
        btnQuanSV.resize(800, 496)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        btnQuanSV.setFont(font)
        self.centralwidget = QtWidgets.QWidget(btnQuanSV)
        self.centralwidget.setObjectName("centralwidget")
        self.btnQuanLyTK = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuanLyTK.setGeometry(QtCore.QRect(30, 320, 341, 51))
        self.btnQuanLyTK.setObjectName("btnQuanLyTK")
        self.btnQuanLyHP = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuanLyHP.setGeometry(QtCore.QRect(420, 320, 341, 51))
        self.btnQuanLyHP.setObjectName("btnQuanLyHP")
        self.btnQuanLyLHP = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuanLyLHP.setGeometry(QtCore.QRect(30, 400, 341, 51))
        self.btnQuanLyLHP.setObjectName("btnQuanLyLHP")
        self.btnQuanLySV = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuanLySV.setGeometry(QtCore.QRect(420, 400, 341, 51))
        self.btnQuanLySV.setObjectName("btnQuanLySV")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(700, 10, 84, 29))
        self.btn_logout.setObjectName("btn_logout")
        self.lb_teacher_name = QtWidgets.QLabel(self.centralwidget)
        self.lb_teacher_name.setGeometry(QtCore.QRect(490, 10, 200, 30))
        self.lb_teacher_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_teacher_name.setObjectName("lb_teacher_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        pixmap = QPixmap('logo_small.png')
        self.label_2.setPixmap(pixmap)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 50, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 100, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        btnQuanSV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btnQuanSV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        btnQuanSV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btnQuanSV)
        self.statusbar.setObjectName("statusbar")
        btnQuanSV.setStatusBar(self.statusbar)

        self.retranslateUi(btnQuanSV)
        QtCore.QMetaObject.connectSlotsByName(btnQuanSV)

    def retranslateUi(self, btnQuanSV):
        _translate = QtCore.QCoreApplication.translate
        btnQuanSV.setWindowTitle(_translate("btnQuanSV", "ỨNG DỤNG ĐIỂM DANH BẰNG KHUÔN MẶT"))
        self.btnQuanLyTK.setText(_translate("btnQuanSV", "Quản lý Tài khoản"))
        self.btnQuanLyHP.setText(_translate("btnQuanSV", "Quản lý Học phần"))
        self.btnQuanLyLHP.setText(_translate("btnQuanSV", "Quản lý Lớp học phần"))
        self.btnQuanLySV.setText(_translate("btnQuanSV", "Quản lý Sinh viên"))
        self.btn_logout.setText(_translate("btnQuanSV", "Đăng xuất"))
        self.lb_teacher_name.setText(_translate("btnQuanSV", self.teacher_name))
        self.label.setText(_translate("btnQuanSV", "ỨNG DỤNG ĐIỂM DANH BẰNG KHUÔN MẶT"))
        self.label_3.setText(_translate("btnQuanSV", "QUẢN LÝ DỮ LIỆU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    btnQuanSV = QtWidgets.QMainWindow()
    ui = Ui_btnQuanSV()
    ui.setupUi(btnQuanSV)
    btnQuanSV.show()
    sys.exit(app.exec_())
