# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'uiEditStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):

    def __init__(self, maSV, url_database='data.db'):
        conn = sqlite3.connect(url_database)
        sqlSelect = "SELECT * FROM Sinhviens WHERE maSV = '"+maSV+"';"
        self.result = conn.execute(sqlSelect).fetchone()
        conn.close()
        # print(self.result)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 550)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 120, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.ip_maSV = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_maSV.setGeometry(QtCore.QRect(150, 70, 300, 40))
        self.ip_maSV.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ip_maSV.setObjectName("ip_maSV")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 120, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.ip_HoDem = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_HoDem.setGeometry(QtCore.QRect(150, 140, 300, 40))
        self.ip_HoDem.setObjectName("ip_HoDem")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 140, 120, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.ip_Ten = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_Ten.setGeometry(QtCore.QRect(670, 140, 300, 40))
        self.ip_Ten.setObjectName("ip_Ten")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 120, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.ipNgaySinh = QtWidgets.QLineEdit(self.centralwidget)
        self.ipNgaySinh.setGeometry(QtCore.QRect(150, 210, 300, 40))
        self.ipNgaySinh.setObjectName("ipNgaySinh")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 210, 120, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.cboxGioiTinh = QtWidgets.QComboBox(self.centralwidget)
        self.cboxGioiTinh.setGeometry(QtCore.QRect(670, 210, 200, 40))
        self.cboxGioiTinh.setObjectName("cboxGioiTinh")

        tuple_GT = ("Nam", "Nữ", "Khác")
        for i in range(len(tuple_GT)):
            self.cboxGioiTinh.insertItem(i, tuple_GT[i])

        self.ipNganhHoc = QtWidgets.QLineEdit(self.centralwidget)
        self.ipNganhHoc.setGeometry(QtCore.QRect(150, 280, 500, 40))
        self.ipNganhHoc.setObjectName("ipNganhHoc")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 120, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.ipLop = QtWidgets.QLineEdit(self.centralwidget)
        self.ipLop.setGeometry(QtCore.QRect(150, 350, 501, 40))
        self.ipLop.setObjectName("ipLop")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 120, 40))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.btnSua = QtWidgets.QPushButton(self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(370, 430, 211, 51))
        self.btnSua.setObjectName("btnSua")

        self.lb_images = QtWidgets.QLabel(self.centralwidget)
        self.lb_images.setGeometry(QtCore.QRect(700, 300, 150, 150))
        self.lb_images.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_images.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_images.setText("")
        self.lb_images.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_images.setObjectName("lb_images")
        self.btnSelectFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFile.setGeometry(QtCore.QRect(700, 450, 101, 41))
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.btnSelectFile.setText("chọn ảnh")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.ip_maSV.setText(self.result[0])
        self.ip_HoDem.setText(self.result[1])
        self.ip_Ten.setText(self.result[2])
        self.ipNgaySinh.setText(self.result[3])

        for i in range(len(tuple_GT)):
            if tuple_GT[i] == self.result[4]:
                self.cboxGioiTinh.setCurrentIndex(i)

        self.ipNganhHoc.setText(self.result[5])
        self.ipLop.setText(self.result[6])

        fname = os.getcwd()
        self.imagePath = os.path.join(fname, 'images', self.result[7])
        self.pixmap = QtGui.QPixmap(self.imagePath)
        self.lb_images.setPixmap(self.pixmap)

        # self.btnSua.clicked.connect(self.GetDataInput)
        self.btnSelectFile.clicked.connect(self.putImage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def GetDataInput(self):
        maSV = self.ip_maSV.text()
        hoDem = self.ip_HoDem.text()
        ten = self.ip_Ten.text()
        ngaySinh = self.ipNgaySinh.text()
        gioiTinh = self.cboxGioiTinh.currentData(0)
        nganhHoc = self.ipNganhHoc.text()
        lop = self.ipLop.text()
        # print(maSV, hoDem, ten, ngaySinh, gioiTinh, nganhHoc, lop)
        return maSV, hoDem, ten, ngaySinh, gioiTinh, nganhHoc, lop

    def putImage(self):
        self.imagePath = QtWidgets.QFileDialog.getOpenFileName(filter='(*.png);;(*.jpg)')[0]
        self.pixmap = QtGui.QPixmap(self.imagePath)
        self.lb_images.setPixmap(self.pixmap)

    def getPathImage(self):
        return self.imagePath

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ỨNG DỤNG ĐIỂM DANH BẰNG KHUÔN MẶT"))
        self.label.setText(_translate("MainWindow", "SỬA THÔNG TINH  SINH VIÊN"))
        self.label_2.setText(_translate("MainWindow", "Mã sinh viên"))
        self.label_3.setText(_translate("MainWindow", "Họ đệm"))
        self.label_4.setText(_translate("MainWindow", "Tên"))
        self.label_5.setText(_translate("MainWindow", "Ngày sinh"))
        self.label_6.setText(_translate("MainWindow", "Giới tính"))
        self.label_7.setText(_translate("MainWindow", "Ngành học"))
        self.label_8.setText(_translate("MainWindow", "Lớp"))
        self.btnSua.setText(_translate("MainWindow", "Sửa thông tin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow('2019605003', '../data.db')
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
