# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_subjectclass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):

    def __init__(self):
        self.nameSubjectClass = {}
        self.nameTeacher = {}
        conn = sqlite3.connect('data.db')
        sql_select_name_subject_class = "SELECT tenHP, maHP FROM Hocphans"
        self.nameSubjectClass = conn.execute(sql_select_name_subject_class).fetchall()
        self.nameSubjectClass = dict((key, val) for key, val in self.nameSubjectClass)

        sql_select_name_teacher = "SELECT hoTenGV, maGV FROM Taikhoans WHERE quyen = 'us'"
        self.nameTeacher = conn.execute(sql_select_name_teacher).fetchall()
        self.nameTeacher = dict((key, val) for key, val in self.nameTeacher)

        conn.close()

    def idSCSubjectAndTeacher(self):
        id_subjectClass = self.ip_idSubjectClass.text()
        id_subject = self.nameSubjectClass[self.comboBoxNameSubject.currentData(0)]
        id_teacher = self.nameTeacher[self.comboBoxNameTeacher.currentData(0)]

        # print(self.comboBoxNameSubject.currentData(0))
        # print(self.comboBoxNameTeacher.currentData(0))

        return id_subjectClass, id_subject, id_teacher


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxNameSubject = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxNameSubject.setGeometry(QtCore.QRect(210, 210, 500, 40))
        self.comboBoxNameSubject.setObjectName("comboBoxNameSubject")

        for index, keyval in enumerate(self.nameSubjectClass):
            self.comboBoxNameSubject.insertItem(index, keyval)
        self.comboBoxNameSubject.setCurrentIndex(0)

        self.ip_idSubjectClass = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_idSubjectClass.setGeometry(QtCore.QRect(210, 120, 500, 40))
        self.ip_idSubjectClass.setObjectName("ip_idSubjectClass")
        self.comboBoxNameTeacher = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxNameTeacher.setGeometry(QtCore.QRect(210, 300, 500, 40))
        self.comboBoxNameTeacher.setObjectName("comboBoxNameTeacher")

        for index, keyval in enumerate(self.nameTeacher):
            self.comboBoxNameTeacher.insertItem(index, keyval)
        self.comboBoxNameTeacher.setCurrentIndex(0)

        self.lb_malhp = QtWidgets.QLabel(self.centralwidget)
        self.lb_malhp.setGeometry(QtCore.QRect(30, 120, 160, 40))
        self.lb_malhp.setObjectName("lb_malhp")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 160, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 300, 160, 40))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 800, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_themlhp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_themlhp.setGeometry(QtCore.QRect(280, 380, 200, 50))
        self.btn_themlhp.setObjectName("btn_themlhp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.btn_themlhp.clicked.connect(self.idSubjectAndTeacher)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_malhp.setText(_translate("MainWindow", "Mã lớp học phần"))
        self.label_2.setText(_translate("MainWindow", "Tên học phần"))
        self.label_3.setText(_translate("MainWindow", "Tên giáo viên"))
        self.label.setText(_translate("MainWindow", "THÊM LỚP HỌC PHẦN"))
        self.btn_themlhp.setText(_translate("MainWindow", "Thêm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
