# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):

    error_login = None
    id_teacher = ""
    teacher_name = ""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPushButton#btn_dangky:hover{\n"
"    color:#8db0ff;\n"
"}\n"
"QPushButton#btn_dangnhap:hover{\n"
"    color:#FFF;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")

        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(250, 70, 100, 100))
        self.logo.setText("")
        self.logo.setObjectName("logo")

        pixmap = QPixmap('logo_small.png')
        self.logo.setPixmap(pixmap)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 290, 220, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.input_tendangnhap = QtWidgets.QLineEdit(self.centralwidget)
        self.input_tendangnhap.setGeometry(QtCore.QRect(100, 230, 400, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.input_tendangnhap.setFont(font)
        self.input_tendangnhap.setObjectName("input_tendangnhap")
        self.input_matkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.input_matkhau.setGeometry(QtCore.QRect(100, 320, 400, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.input_matkhau.setFont(font)
        self.input_matkhau.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_matkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_matkhau.setObjectName("input_matkhau")
        self.btn_dangnhap = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dangnhap.setGeometry(QtCore.QRect(230, 390, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btn_dangnhap.setFont(font)
        self.btn_dangnhap.setStyleSheet("background-color:#58b2ff;\n"
"border-radius:10px;")
        self.btn_dangnhap.setObjectName("btn_dangnhap")
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        # self.btn_dangnhap.clicked.connect(self.Login)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def Login(self):
    #     conn = sqlite3.connect("data.db")
    #     sql_login = "SELECT maGV, hoTenGv,tenDangNhap, matKhau FROM Taikhoans WHERE tenDangNhap = '" + self.input_tendangnhap.text() + "' AND matKhau = '" + self.input_matkhau.text() + "';"
    #     # print(sql_login)
    #     result = conn.execute(sql_login)
    #     user_name = None
    #     pass_word = None
    #     for item in result:
    #         self.id_teacher = item[0]
    #         self.teacher_name = item[1]
    #         user_name = item[2]
    #         pass_word = item[3]
    #
    #     conn.close()
    #     if user_name != self.input_tendangnhap.text() or pass_word != self.input_matkhau.text():
    #         self.error_login = True
    #     else:
    #         self.error_login = False
    #     print("ERROR LOGIN: ", self.error_login)
    #     print(f"Teacher ID: {self.id_teacher}, Teacher Name: {self.teacher_name}")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ỨNG DỤNG ĐIỂM DANH BẰNG KHUÔN MẶT"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_2.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu"))
        self.input_tendangnhap.setPlaceholderText(_translate("MainWindow", "Username"))
        self.input_matkhau.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_dangnhap.setText(_translate("MainWindow", "Đăng nhập"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
